
[theme]
primaryColor = "#1f77b4"
backgroundColor = "#f8fafc"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#222"
font = "sans serif"
[general]
# Nome personalizado para o menu lateral
appTitle = "ðŸŽ« GestÃ£o de Rifas"

[server]
headless = true
port = 8501
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[runner]
magicEnabled = true
fastReruns = true
